@startuml usecase.puml

left to right direction

actor "Utilisateur" as User
actor "Administrateur" as Admin

rectangle "Site de Jeux Vidéo GameZone"{
    usecase "Se connecter" as AUTH

    usecase "Parcourir les jeux" as UC1
    usecase "Filtrer par catégorie" as UC2
    usecase "Gérer le panier" as UC3
    usecase "Passer commande" as UC4
    usecase "Ajouter un nouveau jeu" as UC5

    note right of AUTH
    La fonction de connexion est simulée donc
    l'administrateur n'a pas besoin de se connecter
    pour ajouter un jeu
    end note  
}

Admin -|> User 
User --> UC1
User --> UC3
User --> UC4
User --> AUTH

Admin --> UC5

UC1 <.. UC2 : <<extend>>

@enduml
